require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SlidersController do

  # This should return the minimal set of attributes required to create a valid
  # Slider. As you add validations to Slider, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SlidersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all sliders as @sliders" do
      slider = Slider.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sliders).should eq([slider])
    end
  end

  describe "GET show" do
    it "assigns the requested slider as @slider" do
      slider = Slider.create! valid_attributes
      get :show, {:id => slider.to_param}, valid_session
      assigns(:slider).should eq(slider)
    end
  end

  describe "GET new" do
    it "assigns a new slider as @slider" do
      get :new, {}, valid_session
      assigns(:slider).should be_a_new(Slider)
    end
  end

  describe "GET edit" do
    it "assigns the requested slider as @slider" do
      slider = Slider.create! valid_attributes
      get :edit, {:id => slider.to_param}, valid_session
      assigns(:slider).should eq(slider)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Slider" do
        expect {
          post :create, {:slider => valid_attributes}, valid_session
        }.to change(Slider, :count).by(1)
      end

      it "assigns a newly created slider as @slider" do
        post :create, {:slider => valid_attributes}, valid_session
        assigns(:slider).should be_a(Slider)
        assigns(:slider).should be_persisted
      end

      it "redirects to the created slider" do
        post :create, {:slider => valid_attributes}, valid_session
        response.should redirect_to(Slider.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved slider as @slider" do
        # Trigger the behavior that occurs when invalid params are submitted
        Slider.any_instance.stub(:save).and_return(false)
        post :create, {:slider => {}}, valid_session
        assigns(:slider).should be_a_new(Slider)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Slider.any_instance.stub(:save).and_return(false)
        post :create, {:slider => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested slider" do
        slider = Slider.create! valid_attributes
        # Assuming there are no other sliders in the database, this
        # specifies that the Slider created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Slider.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => slider.to_param, :slider => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested slider as @slider" do
        slider = Slider.create! valid_attributes
        put :update, {:id => slider.to_param, :slider => valid_attributes}, valid_session
        assigns(:slider).should eq(slider)
      end

      it "redirects to the slider" do
        slider = Slider.create! valid_attributes
        put :update, {:id => slider.to_param, :slider => valid_attributes}, valid_session
        response.should redirect_to(slider)
      end
    end

    describe "with invalid params" do
      it "assigns the slider as @slider" do
        slider = Slider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Slider.any_instance.stub(:save).and_return(false)
        put :update, {:id => slider.to_param, :slider => {}}, valid_session
        assigns(:slider).should eq(slider)
      end

      it "re-renders the 'edit' template" do
        slider = Slider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Slider.any_instance.stub(:save).and_return(false)
        put :update, {:id => slider.to_param, :slider => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested slider" do
      slider = Slider.create! valid_attributes
      expect {
        delete :destroy, {:id => slider.to_param}, valid_session
      }.to change(Slider, :count).by(-1)
    end

    it "redirects to the sliders list" do
      slider = Slider.create! valid_attributes
      delete :destroy, {:id => slider.to_param}, valid_session
      response.should redirect_to(sliders_url)
    end
  end

end
